# Generated by Django 4.1.2 on 2022-11-20 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_rename_project_portfolio_tarproject_portfolio_iszip_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='isZip',
        ),
    ]
