# Generated by Django 4.1.2 on 2022-11-30 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_remove_portfolio_iszip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='tarproject',
            field=models.FileField(blank=True, null=True, upload_to='staticfiles/portfolio'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='zipproject',
            field=models.FileField(blank=True, null=True, upload_to='staticfiles/portfolio'),
        ),
    ]
